/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "s21_string.h"

START_TEST(strcmp1)
{
char s1[20] = "Hello world\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "";
char s10[20] = "Hello world\0";

ck_assert_int_eq(s21_strcmp(s4, s5), strcmp(s4, s5));
ck_assert_int_eq(s21_strcmp(s5, s7), strcmp(s5, s7));
ck_assert_int_eq(s21_strcmp(s3, s4), strcmp(s3, s4));
ck_assert_int_eq(s21_strcmp(s6, s7), strcmp(s6, s7));
ck_assert_int_eq(s21_strcmp(s8, s9), strcmp(s8, s9));
ck_assert_int_eq(s21_strcmp(s1, s10), strcmp(s1, s10));

}
END_TEST

START_TEST(strncmp1)
{
char s1[20] = "Hello world\0";
char s2[15] = "Hello world\n\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "";
    
ck_assert_int_eq(s21_strncmp(s1, s2, 11), strncmp(s1, s2, 11));
ck_assert_int_eq(s21_strncmp(s1, s2, 12), strncmp(s1, s2, 12));
ck_assert_int_eq(s21_strncmp(s4, s5, 1), strncmp(s4, s5, 1));
ck_assert_int_eq(s21_strncmp(s4, s5, 2), strncmp(s4, s5, 2));
ck_assert_int_eq(s21_strncmp(s5, s7, 1), strncmp(s5, s7, 1));
ck_assert_int_eq(s21_strncmp(s5, s7, 2), strncmp(s5, s7, 2));
ck_assert_int_eq(s21_strncmp(s3, s4, 2), strncmp(s3, s4, 2));
ck_assert_int_eq(s21_strncmp(s3, s4, 3), strncmp(s3, s4, 3));
ck_assert_int_eq(s21_strncmp(s6, s7, 1), strncmp(s6, s7, 1));
ck_assert_int_eq(s21_strncmp(s6, s7, 2), strncmp(s6, s7, 2));
ck_assert_int_eq(s21_strncmp(s8, s9, 3), strncmp(s8, s9, 3));

}
END_TEST

START_TEST(strcpy1)
{
char s1[20] = "Hello world\0";
char s2[15] = "Hello world\n\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "D";
char s10[20] = "Hello world\0";
char s11[20] = "hello world";
char s12[8] = "Q";

ck_assert_str_eq(s21_strcpy(s11, s12), strcpy(s11, s12));
ck_assert_str_eq(s21_strcpy(s3, s4), strcpy(s3, s4));
ck_assert_str_eq(s21_strcpy(s1, s2), strcpy(s1, s2));
ck_assert_str_eq(s21_strcpy(s10, s8), strcpy(s10, s8));
ck_assert_str_eq(s21_strcpy(s5, s6), strcpy(s5, s6));
ck_assert_str_eq(s21_strcpy(s1, s10), strcpy(s1, s10));
ck_assert_str_eq(s21_strcpy(s5, s7), strcpy(s5, s7));
ck_assert_str_eq(s21_strcpy(s8, s9), strcpy(s8, s9));
ck_assert_str_eq(s21_strcpy(s6, s7), strcpy(s6, s7));

}
END_TEST

START_TEST(strncpy1)
{
char s1[20] = "Hello world\0";
char s2[15] = "Hello world\n\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "D";
char s10[20] = "Hello world\0";
char s11[20] = "hello world";
char s12[8] = "Q";

ck_assert_str_eq(s21_strncpy(s11, s12, 2), strncpy(s11, s12, 2));
ck_assert_str_eq(s21_strncpy(s3, s4, 1), strncpy(s3, s4, 1));
ck_assert_str_eq(s21_strncpy(s1, s2, 3), strncpy(s1, s2, 3));
ck_assert_str_eq(s21_strncpy(s10, s8, 2), strncpy(s10, s8, 2));
ck_assert_str_eq(s21_strncpy(s5, s6, 1), strncpy(s5, s6, 1));
ck_assert_str_eq(s21_strncpy(s1, s9, 7), strncpy(s1, s9, 7));
ck_assert_str_eq(s21_strncpy(s5, s7, 1), strncpy(s5, s7, 1));
ck_assert_str_eq(s21_strncpy(s8, s9, 2), strncpy(s8, s9, 2));
ck_assert_str_eq(s21_strncpy(s6, s7, 1), strncpy(s6, s7, 1));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strcmp1);
    tcase_add_test(tc1_1, strncmp1);
    tcase_add_test(tc1_1, strcpy1);
    tcase_add_test(tc1_1, strncpy1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
